Add: 로그인, 회원가입, 소셜로그인 기능 구현
wecode-bootcamp-korea/26-2nd-WeAreBnB-backend pull request #7
Opened 2021-11-19 05:10 UTC by minjeongcode

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현, 카카오 소셜 로그인 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입 기능 구현
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현
- bcrypt 패스워드 암호화

2. 로그인 기능 구현
- 로그인 시 JWT토큰 발행(유효시간 설정)
- bcrypt 패스워드 복호화
- 비활성화 계정 로그인 시 에러메세지 반환

3. 카카오 소셜 로그인 기능 구현
- 카카오 로그인시 발행된 토큰이 없을 시 에러메세지 반환
- 카카오에 유저 정보 요청 후 DB에 데이터 저장
- JWT 토큰 발행
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- self 함수를 이용해서 post뷰 안에 조건문을 줄여볼 수 있어서 좋았고 JWT 유효시간 설정 추가하는 방법도 알게되어서 재밌었습니다.
- 소셜 로그인 구현을 위해 공식문서를 봤지만 공식문서에 나와있는 안내로 코드를 작성하는 걸 연결하는게 힘들었습니다. 공식문서를 보면서 어떤식으로 접근해야하는지 잘 모르겠습니다. 
<br />

## :: 기타 질문 및 특이 사항

2021-11-19 05:11 UTC, minjeongcode commented
유닛테스트 하기 전 코드입니다.

2021-11-19 07:20 UTC, Kang-kyunghun commented on users/views.py
> +
```suggestion
            user, created = User.objects.get_or_create(social_id = social_id, email = email)
            
            if created:
                user.name = name,
                user.social_type = "kakao"
                user.save
            
```
```suggestion
            user, created = User.objects.get_or_create(social_id = social_id, email = email, defaults={'social_type': 'kakao', 'name' : 'angel')
    
```

2021-11-19 08:23 UTC, Kang-kyunghun requested changes

2021-11-19 08:23 UTC, Kang-kyunghun commented on users/views.py
> +from users.models    import User
```suggestion
from datetime        import datetime, timedelta
from django.http     import JsonResponse
from django.views    import View

from config.settings import SECRET_KEY, ALGORITHM
from users.models    import User
```

2021-11-19 08:23 UTC, Kang-kyunghun commented on users/views.py
> +
1. requests 모듈을 사용하실 때에는 timeout 옵션을 반드시 설정해주셔야 합니다.
그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다. timeout 옵션을 추가해 주세요.
```suggestion
            kakao_response = requests.get(kakao_url, headers = headers, timeout=5).json()
            
```

2.  kakao로부터 항상 올바른 응답(200)을 받는다는 보장은 없습니다. 카카오로부터 에러코드를 받을 경우에 대해서 어떻게 처리해야 할지 생각해보고 코드에 예외처리 추가해 주세요.

2021-11-19 08:23 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse({'message' : 'INVALID_TOKEN'})
```suggestion
            if not kakao_token:
                return JsonResponse({'message' : 'INVALID_TOKEN'})
```

2021-11-21 07:42 UTC, minjeongcode commented on users/views.py
> +
리뷰 반영했습니다.

2021-11-21 07:43 UTC, minjeongcode commented on users/views.py
> +from users.models    import User
리뷰 반영했습니다.

2021-11-21 07:43 UTC, minjeongcode commented on users/views.py
> +
리뷰 반영하여 timeout, key_error 추가하였습니다.

2021-11-21 07:43 UTC, minjeongcode commented on users/views.py
> +                return JsonResponse({'message' : 'INVALID_TOKEN'})
코드 수정하였습니다.

2021-11-22 06:13 UTC, Kang-kyunghun commented
LGTM~~!! 👍

2021-11-22 06:13 UTC, merged